include:
  - project: wiley-sons/tc-gitlab-templates
    file: autodevops-gradle.gitlab-ci.yml
    ref: bugfix/build-issue-SRE-4227
    
variables:
  APP_NAME: eventhub
  AUTO_DEVOPS_DEPLOY_DEBUG: "true"

build:
  variables:
    BP_JVM_VERSION: "11.*"
    BP_GRADLE_BUILT_ARTIFACT: "app/build/libs/*.[jw]ar"
    BP_GRADLE_BUILD_ARGUMENTS: ":app:bootJar"
    AUTO_DEVOPS_BUILD_IMAGE_FORWARDED_CI_VARIABLES: "BP_GRADLE_BUILT_ARTIFACT,BP_GRADLE_BUILD_ARGUMENTS,BP_JVM_VERSION"
    #APP_NAME: eventhub
    #IMAGE_NAME: $CI_REGISTRY/tc/$APP_NAME:latest
  #image:
    #name: gradle:5.3.1-jdk11-slim
  #before_script: 
    #- echo "JAVA_HOME"
    #- echo $JAVA_HOME
    #- export JAVA_HOME="/docker-java-home"
    #- echo $JAVA_HOME
    #- sh $CI_PROJECT_DIR/gradlew build
  #artifacts:
    #paths:
      #- app/build/libs/*.[jw]ar
  
  #image:
    #name: quay.io/podman/stable
  script:
    - pack config trusted-builders add paketo-buildpacks/gradle
    - pack config trusted-builders add paketo-buildpacks/apache-tomcat
    - pack config trusted-builders add paketo-buildpacks/spring-boot
    - pack config trusted-builders add paketo-buildpacks/dist-zip
    - pack config trusted-builders add paketo-buildpacks/ca-certificates
    - pack config trusted-builders add paketo-buildpacks/bellsoft-liberica
    - pack config trusted-builders add paketo-buildpacks/syft
    - pack config trusted-builders add paketo-buildpacks/liberty
    - /build/build.sh
    #- podman login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    #- podman build -t "$IMAGE_NAME" .
    #- podman push "$IMAGE_NAME"

review:
  variables:
    KUBE_NAMESPACE: epdcs-review
    K8S_SECRET_SPRING_PROFILES_ACTIVE: review
    HELM_UPGRADE_VALUES_FILE: .gitlab/auto-deploy-values-review.yaml
  after_script:
    - echo "HOST_IP=$(kubectl get pods -l app=$APP_NAME-$CI_ENVIRONMENT_SLUG --sort-by=.metadata.creationTimestamp -o jsonpath='{.items[-1:]..status.podIP}' -n epdcs-review)" >> deploy.env
stop_review:
  variables:
    KUBE_NAMESPACE: epdcs-review

review-integrationtest:
  image: artifactory.aws.wiley.com/docker/openjdk:11-jdk
  tags:
    - dev
  extends: .review-integration-test
  variables:
    ENVIRONMENT_HOST: environment_url.txt
  script:
    - echo "$HOST_IP"
    - "TEST_ENV=review NAKADI_BASE_URL=http://$HOST_IP POSTGRES_URL=jdbc:postgresql://$HOST_IP:5432/local_nakadi_db ZOOKEEPER_URL=$HOST_IP:2181 KAFKA_URL=$HOST_IP:29092 ./gradlew :acceptance-test:acceptanceTest"

dev:
  variables:
    KUBE_NAMESPACE: epdcs-dev
    K8S_SECRET_SPRING_PROFILES_ACTIVE: dev
    KUBE_INGRESS_BASE_DOMAIN: dev.tc.private.wiley.host
    HELM_UPGRADE_VALUES_FILE: .gitlab/auto-deploy-values-dev.yaml


dev-integrationtest:
  when: manual
  image: artifactory.aws.wiley.com/docker/openjdk:11-jdk
  tags:
    - dev
  variables:
    APP_ENVIRONMENT: dev
  allow_failure: true
  extends: .dev-integration-test
  script:
    - "TEST_ENV=dev POSTGRES_PWD=$EVENTHUB_DB_PASSWORD_DEV ./gradlew :acceptance-test:acceptanceTest"

qa:
  variables:
    KUBE_NAMESPACE: epdcs-qa
    K8S_SECRET_SPRING_PROFILES_ACTIVE: qa
    KUBE_INGRESS_BASE_DOMAIN: qa.tc.wiley.host
    HELM_UPGRADE_VALUES_FILE: .gitlab/auto-deploy-values-qa.yaml

qa-integrationtest:
  when: manual
  image: artifactory.aws.wiley.com/docker/openjdk:11-jdk
  tags:
    - dev
  variables:
    APP_ENVIRONMENT: qa
  allow_failure: true
  extends: .qa-integration-test
  script:
    - "TEST_ENV=qa POSTGRES_PWD=$EVENTHUB_DB_PASSWORD_QA ./gradlew :acceptance-test:acceptanceTest"

uat:
  variables:
    KUBE_NAMESPACE: epdcs-uat
    K8S_SECRET_SPRING_PROFILES_ACTIVE: uat
    KUBE_INGRESS_BASE_DOMAIN: uat.tc.wiley.host
    HELM_UPGRADE_VALUES_FILE: .gitlab/auto-deploy-values-uat.yaml

uat-integrationtest:
  when: manual
  image: artifactory.aws.wiley.com/docker/openjdk:11-jdk
  tags:
    - uat
  variables:
    APP_ENVIRONMENT: uat
  allow_failure: true
  extends: .uat-integration-test
  script:
    - "TEST_ENV=uat POSTGRES_PWD=$EVENTHUB_DB_PASSWORD_UAT ./gradlew :acceptance-test:acceptanceTest"
