include:
  - project: wiley-sons/tc-gitlab-templates
    file: autodevops-gradle.gitlab-ci.yml
    ref: latest_image

variables:
  APP_NAME: eventhub
  AUTO_DEVOPS_DEPLOY_DEBUG: "true"
  TEST_DISABLED: "true"
  DEV_DISABLED: "true"

build:
  variables:
    BP_JVM_VERSION: "11.*"
    BP_GRADLE_BUILT_ARTIFACT: "app/build/libs/*.[jw]ar"
    BP_GRADLE_BUILD_ARGUMENTS: ":app:bootJar"
    AUTO_DEVOPS_BUILD_IMAGE_FORWARDED_CI_VARIABLES: "BP_GRADLE_BUILT_ARTIFACT,BP_GRADLE_BUILD_ARGUMENTS"


review:
  variables:
    KUBE_NAMESPACE: epdcs-review
    K8S_SECRET_SPRING_PROFILES_ACTIVE: review
    HELM_UPGRADE_VALUES_FILE: .gitlab/auto-deploy-values-review.yaml

dev:
  extends: .auto-deploy
  stage: dev
  tags:
    - dev  # gitlab runner tag, correspond to a environment
  variables:
    KUBE_NAMESPACE: epdcs-dev
    KUBE_INGRESS_BASE_DOMAIN: dev.tc.private.wiley.host
    HELM_UPGRADE_VALUES_FILE: .gitlab/auto-deploy-values-dev.yaml
  environment:
    name: dev
    kubernetes:
      namespace: ${KUBE_NAMESPACE}
    url: https://$APP_NAME.$KUBE_INGRESS_BASE_DOMAIN
  rules:
    - if: '$DEV_DISABLED == "true"'
      when: never
    - !reference [.default-deploy-rules, rules]
