sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop
  - pip install --user codecov
  - curl http://www.jpm4j.org/install/script | sudo sh
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
  

# run tests
script:
  - gradle check fullAcceptanceTest --stacktrace

after_success:
  - codecov
  - CODACY_PROJECT_TOKEN=3b80c14af47147a185d106c4666d4999 codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

