sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

# fix for buffer overflow https://github.com/travis-ci/travis-ci/issues/5227
addons:
  hostname: localhost

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.cache/pip/log/debug.log

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.cache/pip

before_install:
  - docker --version
  # install docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - pip install --user codecov
  - sudo curl -L https://github.com/codacy/codacy-coverage-reporter/releases/download/1.0.13/codacy-coverage-reporter-assembly-1.0.5.jar > /opt/codacy-coverage-reporter.jar

install:
  - ./gradlew compileJava compileTestJava assemble

before_script:
  - sudo /etc/init.d/postgresql stop

env:
  global:
    - DOCKER_COMPOSE_VERSION="1.23.1"
  matrix:
    - TEST_SUITE="./gradlew checkstyle --stacktrace"                  # checkstyle
    - TEST_SUITE="travis_wait ./gradlew testWithReport --stacktrace"  # unit tests with coverage report
    - TEST_SUITE="./gradlew fullAcceptanceTest --stacktrace"          # acceptances tests

# run test suits in parallel
script: "$TEST_SUITE"

after_success:
  # only testWithReport generates coverage report
  - test -e build/reports/jacoco/test/jacocoTestReport.xml && codecov
  - test -e build/reports/jacoco/test/jacocoTestReport.xml && java -jar /opt/codacy-coverage-reporter.jar -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
