sudo: required

language: java

jdk:
  - openjdk8

services:
  - docker

before_script:
  - pip install --user codecov
  - curl http://www.jpm4j.org/install/script | sudo sh
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly

# run test suits in parallel
script: gradle checkstyle --stacktrace

after_success:
  - codecov
  - codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml