service:
  internalPort: 8080
  externalPort: 5000
ingress:
  enabled: true
  ingressClass: "nginx-external"
  path: "/"
  tls:
    enabled: false
livenessProbe:
  path: "/health"
  initialDelaySeconds: 120
  timeoutSeconds: 15
  scheme: "HTTP"
  probeType: "httpGet"
readinessProbe:
  path: "/health"
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 3
  failureThreshold: 10
  scheme: "HTTP"
  probeType: "httpGet"
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::281595016440:role/eventhub-uat-uat-use1
  createNew: true
externalSecrets:
  enabled: true
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: nakadi-eventhub-uat-event_hub_user
prometheusOperator:
  serviceMonitor:
    enabled: true
    path: "/prometheus"
application:
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: uat
resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1500m
    memory: 1Gi
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50